### ISSUE TITLE
Crash when trying delete complicated track

### ISSUE THREAD

**Issue by donarturo11** [muse-sequencer/muse#1084]
**Describe the bug**
Trying delete more complicated track finishes with crash

**To Reproduce**
1. Go to selected track (see attached picture)
2. Right click to context menu
3. Choose 'Delete Track'
4. Program crashes: 
5. See error:
```
JACK: port connections changed: A:30 B:13 isConnect:1
JACK: port connections changed: A:31 B:14 isConnect:1
MusE: STARTING Heartbeat timer
MusE::seqStart: getting audio driver MusEGlobal::realTimePriority:5
[New Thread 0x7fffda8a16c0 (LWP 4714)]
graph_callback()
Thread <Prefetch, id 0x7fffda8a16c0> has SCHED_OTHER priority 0
unknown kbAccel 0x1000020
ACTIVE TOPWIN CHANGED to '<None>' ((nil))
ACTIVE TOPWIN CHANGED to 'Arranger' (0x5555558035b0)
ACTIVE TOPWIN CHANGED to '<None>' ((nil))
ACTIVE TOPWIN CHANGED to 'Arranger' (0x5555558035b0)
ACTIVE TOPWIN CHANGED to '<None>' ((nil))
ACTIVE TOPWIN CHANGED to 'Arranger' (0x5555558035b0)
double free or corruption (fasttop)

Thread 9 "muse4" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffda9226c0 (LWP 4711)]
0x00007ffff36a14dc in ?? () from /usr/lib/libc.so.6
(gdb) bt full
#0  0x00007ffff36a14dc in  () at /usr/lib/libc.so.6
#1  0x00007ffff3651998 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff363b53d in abort () at /usr/lib/libc.so.6
#3  0x00007ffff369567e in  () at /usr/lib/libc.so.6
#4  0x00007ffff36ab26c in  () at /usr/lib/libc.so.6
#5  0x00007ffff36ad042 in  () at /usr/lib/libc.so.6
#6  0x00007ffff36afa33 in free () at /usr/lib/libc.so.6
#7  0x00007ffff7b6c152 in std::__new_allocator<std::_Rb_tree_node<std::pair<unsigned int const, MusECore::MidiCtrlVal> > >::deallocate(std::_Rb_tree_node<std::pair<unsigned int const, MusECore::MidiCtrlVal> >*, unsigned long) (this=0x55555707da00, __p=0x5555576f1270, __n=1)
    at /usr/include/c++/12.2.0/bits/new_allocator.h:158
#8  0x00007ffff7b6becf in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<unsigned int const, MusECore::MidiCtrlVal> > > >::deallocate(std::allocator<std::_Rb_tree_node<std::pair<unsigned int const, MusECore::MidiCtrlVal> > >&, std::_Rb_tree_node<std::pair<unsigned int const, MusECore::MidiCtrlVal> >*, unsigned long) (__a=..., __p=0x5555576f1270, __n=1)
    at /usr/include/c++/12.2.0/bits/alloc_traits.h:496
#9  0x00007ffff7b6b9cb in std::_Rb_tree<unsigned int, std::pair<unsigned int const, MusECore::MidiCtrlVal>, std::_Select1st<std::pair<unsigned int const, MusECore::MidiCtrlVal> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, MusECore::MidiCtrlVal> > >::_M_put_node(std::_Rb_tree_node<std::pair<unsigned int const, MusECore::MidiCtrlVal> >*) (this=0x55555707da00, __p=0x5555576f1270)
    at /usr/include/c++/12.2.0/bits/stl_tree.h:565
#10 0x00007ffff7b6ac86 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, MusECore::MidiCtrlVal>, std::_Select1st<std::pair<unsigned int const, MusECore::MidiCtrlVal> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, MusECore::MidiCtrlVal> > >::_M_drop_node(std::_Rb_tree_node<std::pair<unsigned int const, MusECore::MidiCtrlVal> >*) (this=0x55555707da00, __p=0x5555576f1270)
    at /usr/include/c++/12.2.0/bits/stl_tree.h:632
#11 0x00007ffff7b6b84c in std::_Rb_tree<unsigned int, std::pair<unsigned int const, MusECore::MidiCtrlVal>, std::_Select1st<std::pair<unsigned int const, MusECore::MidiCtrlVal> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, MusECore::MidiCtrlVal> > >::_M_erase_aux(std::_Rb_tree_const_iterator<std::pair<unsigned int const, MusECore::MidiCtrlVal> >)
     (this=0x55555707da00, __position={first = 120772, second = {part = 0x7fffe80088b0, val = 118}}) at /usr/include/c++/12.2.0/bits/stl_tree.h:2495
        __y = 0x5555576f1270
#12 0x00007ffff7b6aa2c in std::_Rb_tree<unsigned int, std::pair<unsigned int const, MusECore::MidiCtrlVal>, std::_Select1st<std::pair<unsigned int const, MusECore::MidiCtrlVal> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, MusECore::MidiCtrlVal> > >::erase[abi:cxx11](std::_Rb_tree_iterator<std::pair<unsigned int const, MusECore::MidiCtrlVal> >)
     (this=0x55555707da00, __position={first = 120772, second = {part = 0x7fffe80088b0, val = 118}}) at /usr/include/c++/12.2.0/bits/stl_tree.h:1209
        __result = {first = 120772, second = {part = 0x7fffe80088b0, val = 118}}
#13 0x00007ffff7b6a161 in std::multimap<unsigned int, MusECore::MidiCtrlVal, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, MusECore::MidiCtrlVal> > >::erase[abi:cxx11](std::_Rb_tree_iterator<std::pair<unsigned int const, MusECore::MidiCtrlVal> >)
    (this=0x55555707da00, __position={first = 120772, second = {part = 0x7fffe80088b0, val = 118}})
    at /usr/include/c++/12.2.0/bits/stl_multimap.h:713
#14 0x00007ffff7ba1f44 in MusECore::PendingOperationItem::executeRTStage() (this=0x555557b66dd0)
    at /home/arch/art/MusE-sequencer-develop/muse/src/muse/operations.cpp:1282
        flags = {_flagsLo = 0, _flagsHi = 0, _sender = 0x0}
#15 0x00007ffff7ba385d in MusECore::PendingOperationList::executeRTStage() (this=0x555555c3a048)
    at /home/arch/art/MusE-sequencer-develop/muse/src/muse/operations.cpp:1837
--Type <RET> for more, q to quit, c to continue without paging--c
        ip = {_type = MusECore::PendingOperationItem::DeleteMidiCtrlVal, {_part = 0x7ffff7fda3e2, _midi_port = 0x7ffff7fda3e2, _void_track_list = 0x7ffff7fda3e2, _audioSamplesLen = 0x7ffff7fda3e2, _src_aud_ctrl_list_list = 0x7ffff7fda3e2}, {_orig_event_list = 0x5, _orig_mcvl = 0x5, _mcvll = 0x5, _aud_ctrl_list_list = 0x5, _orig_tempo_list = 0x5, _orig_sig_list = 0x5, _orig_key_list = 0x5, _stretch_list = 0x5, _part_list = 0x5, _track_list = 0x5, _midi_device_list = 0x5, _midi_instrument_list = 0x5, _aux_send_value_list = 0x5, _route_list = 0x5, _orig_marker_list = 0x5, _audioSamplesPointer = 0x5, _metroAccentsMap = 0x5}, {_event_list = 0x55555707da00, _midi_instrument = 0x55555707da00, _midi_device = 0x55555707da00, _track = 0x55555707da00, _mcvl = 0x55555707da00, _aud_ctrl_list = 0x55555707da00, _marker_list = 0x55555707da00, _tempo_list = 0x55555707da00, _sig_list = 0x55555707da00, _key_list = 0x55555707da00, _dst_route_pointer = 0x55555707da00, _newAudioSamples = 0x55555707da00, _bool_pointer = 0x55555707da00, _newMetroAccentsMap = 0x55555707da00, _audio_converter_settings = 0x55555707da00}, _iPart = non-dereferenceable iterator for associative container, _ev = {_vptr.Event = 0x7ffff7e32730 <vtable for MusECore::Event+16>, ev = 0x0}, _iev = non-dereferenceable iterator for associative container, _imcv = {first = 120772, second = {part = 0x7fffe80088b0, val = 118}}, _iCtrl = non-dereferenceable iterator for associative container, _iCtrlList = non-dereferenceable iterator for associative container, _iStretchEvent = non-dereferenceable iterator for associative container, _iMidiInstrument = non-dereferenceable iterator for std::list, _iMidiDevice = non-dereferenceable iterator for std::list, _iRoute = non-dereferenceable iterator for std::vector, _iMarker = non-dereferenceable iterator for associative container, _src_route = {{track = 0x0, device = 0x0, jackPort = 0x0, voidPointer = 0x0}, midiPort = -1, channel = -1, channels = -1, remoteChannel = -1, type = MusECore::Route::TRACK_ROUTE, persistentJackPortName = '\000' <repeats 255 times>, audioLatencyOut = 0}, _dst_route = {{track = 0x0, device = 0x0, jackPort = 0x0, voidPointer = 0x0}, midiPort = -1, channel = -1, channels = -1, remoteChannel = -1, type = MusECore::Route::TRACK_ROUTE, persistentJackPortName = '\000' <repeats 255 times>, audioLatencyOut = 0}, _sndFileR = {sf = 0x0}, {_intA = -139459232, _uintA = 4155508064, _posLenVal = 4155508064, _boolA = 96, _name = 0x7ffff7b00560 <std::_Rb_tree_node<std::pair<unsigned int const, MusECore::Event> >::_M_valptr() const+28>, _aux_send_value = 6.9533489176334517e-310, _insert_at = -139459232, _from_idx = -139459232, _address_client = -139459232, _rw_flags = -139459232, _newAudioSamplesLen = -139459232, _drum_map_track_operation = 0x7ffff7b00560 <std::_Rb_tree_node<std::pair<unsigned int const, MusECore::Event> >::_M_valptr() const+28>, _drum_map_track_patch_operation = 0x7ffff7b00560 <std::_Rb_tree_node<std::pair<unsigned int const, MusECore::Event> >::_M_valptr() const+28>, _drum_map_track_patch_replace_operation = 0x7ffff7b00560 <std::_Rb_tree_node<std::pair<unsigned int const, MusECore::Event> >::_M_valptr() const+28>, _midi_ctrl_val_remap_operation = 0x7ffff7b00560 <std::_Rb_tree_node<std::pair<unsigned int const, MusECore::Event> >::_M_valptr() const+28>, _museFrame = 140737348896096, _audio_converter = 0x7ffff7b00560 <std::_Rb_tree_node<std::pair<unsigned int const, MusECore::Event> >::_M_valptr() const+28>, _audio_ctrl_paste_erase_opts = 4155508064}, {_intB = -402618088, _uintB = 3892349208, _lenVal = 3892349208, _marker_tick = 3892349208, _selected = 24, _to_idx = -402618088, _address_port = -402618088, _open_flags = -402618088, _ctl_num = -402618088, _ctl_flags = -402618088, _stretch_type = -402618088, _audio_converter_ui = 0x7fffe8008918}, {_intC = 1460459984, _uintC = 1460459984, _ctl_val = 1460459984, _ctl_dbl_val = 4.6355719616741594e-310, _audio_converter_value = 4.6355719616741594e-310, _marker_lock = 208, _audCtrlValStruct = 0x5555570cd9d0}}
        sl = 0x55555768e280
#16 0x00007ffff7c7f185 in MusECore::Song::executeOperationGroup2(MusECore::Undo&) (this=0x555555c37ef0) at /home/arch/art/MusE-sequencer-develop/muse/src/muse/undo.cpp:2153
#17 0x00007ffff7c12978 in MusECore::Song::processMsg(MusECore::AudioMsg*) (this=0x555555c37ef0, msg=0x7fffffffc610) at /home/arch/art/MusE-sequencer-develop/muse/src/muse/song.cpp:2269
#18 0x00007ffff7a8cca5 in MusECore::Audio::processMsg(MusECore::AudioMsg*) (this=0x555555a5c050, msg=0x7fffffffc610) at /home/arch/art/MusE-sequencer-develop/muse/src/muse/audio.cpp:1531
#19 0x00007ffff7a89de9 in MusECore::Audio::process(unsigned int) (this=0x555555a5c050, frames=1024) at /home/arch/art/MusE-sequencer-develop/muse/src/muse/audio.cpp:636
        sn = -627958844
        rv = 0
        ol = 0x7ffff404b000
        jackState = 0
        al = 0x7fffc19a1000
        samplePos = 6648
        offset = 0
#20 0x00007ffff7eb9de4 in MusECore::JackAudioDevice::processAudio(unsigned int, void*) (frames=1024, arg=0x5555558857e0) at /home/arch/art/MusE-sequencer-develop/muse/src/muse/driver/jack.cpp:293
#21 0x00007ffff735f67f in  () at /usr/lib/libjack.so.0
#22 0x00007ffff735edb8 in  () at /usr/lib/libjack.so.0
#23 0x00007ffff737cf51 in  () at /usr/lib/libjack.so.0
#24 0x00007ffff369f78d in  () at /usr/lib/libc.so.6
#25 0x00007ff
ff37208e4 in clone () at /usr/lib/libc.so.6
(gdb) 
```

**Expected behavior**
Track should be deleted

**Screenshots**
![img1](https://user-images.githubusercontent.com/6421054/189208656-d54eea59-f8f0-4f81-a0b4-72081e1fb626.png)

**Desktop (please complete the following information):**
 - OS: Archlinux]
 - Desktop: Xfce

**Additional context**
[muzyka_na_smyczki.zip](https://github.com/muse-sequencer/muse/files/9530023/muzyka_na_smyczki.zip)

**Comment by terminator356** [comment]
(For anyone following this, see the PR, I'm trying to fix several issues with that.)
